---
title: "Test smooth.R"
author: "W. Bauer"
date: "September 8, 2015"
output: html_document
---

```{r}
source("../R/smooth.R")
source("../R/system_matrix_utils.R")
library(Matrix)
```

Construct a test image

```{r fig.show='hold'}
ap <- read.table("../data/acoustic_properties_thigh.csv", sep=',', header=TRUE, as.is=TRUE)
img <- testImage(24,8,1,1/1450) # fat background
img[4:14, 2:5] <- 1/1585  # muscle
img[19:20, 6:7] <- 1/1584 # vessel
img[1, 1:8] <- 1/1660   # skin
img[24, 1:8] <- 1/1660  # skin
plotTestImage(img)
gridOverlay(img)
ys <- probeYs(8, img)
probeOverlay(ys, img, col=c("black", "white"))
M <- genS(8,24,1)
tau <- M %*% as.vector(img)
```

```{r}
ans <- integer()
for(i in 1:nrow(M)){
  if(max(abs(M[i,]-S[i,])) > .1) ans <- c(ans, i)
}
```

```{r}
makevec <- function(img){
  nr <- nrow(img)
  nc <- ncol(img)
  ans <- numeric(nr*nc)
  for(i in 1:nr){
    for(j in 1:nc){
      ans[ij2col(i,j,nr,nc)] <- img[i,j]
    }
  }
  ans
}
```

Problem!!

```{r}
S <- sysMat(ys, img)
# These two vectors should match and they don't
as.vector(img)[which(S[10,]==1)]
as.vector(img)[which(S[19,]==1)]
# Specifically, the 18th entry of the latter is a vessel, not fat.
# That 18th entry corresponds to entry 139 of as.vector(img)
# Entry 139 of S[19,] is 12
```

But, after we change the roles of i and j in ij2col, M[10,]==1, counts sequentially from 9 to 32, but it should count from 25 to 48.

```{r}
M <- genS(8,24,1)
which(M[10,]==1)
```

