---
title: "Utility tests"
date: "03/11/2015"
output: html_document
---

#### Does function `findPixelCrossings` find the right pixel crossings?


```{r fig.align='center', fig.show='hold'}
source("../R/utilities.R")
# Create an 8x8 square grid
hg <- 0:8
vg <- 0:8
# Plot it in a square window
mai <- par("mai")
par(mai=adj_margins())
plot(c(-.25, 8.25), c(-.25, 8.25), type='n', xlab="z", ylab="x", main="Testing findPixelCrossings")
par(mai=mai)
abline(h=hg, lwd=2, col="lightblue")
abline(v=vg, lwd=2, col="lightblue")
# Draw a horizontal line at x = 0.5
abline(h=0.5, lwd=3)
# This line has m=0, b=0.5. Find the pixel crossings
pcs <- findPixelCrossings(hg, vg, 0.5, 0.0)
# Plot them
points(x ~ z, pcs, pch=19, col="red")
# Draw a line from (0, 1.5) to (8, 4.5)
m <- (4.5-0.5)/8
b <- 1.5
abline(b, m, lwd=3)
# Find and plot the pixel crossings
pcs <-findPixelCrossings(hg, vg, b, m)
points(x ~ z, pcs, pch=19, col="blue")
# Draw a line from (0, 7.5) to (8, 6.5)
m <- (6.5-7.5)/8
b <- 7.5
abline(b, m, lwd=3)
# Find and plot the pixel crossings
pcs <-findPixelCrossings(hg, vg, b, m)
points(x ~ z, pcs, pch=19, col="magenta")
```

#### Does function `findLinesCrossingPixel` find the right lines?

Testing a function which finds all lines intersecting a given pixel.

```{r fig.align='center', fig.show='hold'}
testPixel <- function(pixel){
  # Create an 8x8 square grid
  hg <- 0:8
  vg <- 0:8
  # Plot it in a square window
  mai <- par("mai")
  par(mai=adj_margins())
  plot(c(-.25, 8.25), c(-.25, 8.25), type='n', xlab="z", ylab="x", main=paste("Testing pixel (", pixel[1], ",", pixel[2],")"))
  par(mai=mai)
  # Mark the pixel in pink
  rect(pixel[1], pixel[2], pixel[1]+1, pixel[2]+1, col="pink")
  abline(h=hg, lwd=2, col="lightblue")
  abline(v=vg, lwd=2, col="lightblue")
  # Put a transmitter array at z=0 and a receiver array at z=8
  xmit <- .5+0:7
  zxmit <- 0
  rcv <- .5+0:7
  zrcv <- 8
  points(rep(zxmit,8), xmit, pch=15)
  points(rep(zrcv,8), rcv, pch=0)
  crossers <- findLinesCrossingPixel(pixel, pixel+1, xmit, zxmit, rcv, zrcv)
  for(i in 1:length(xmit)){
    for(xcoord in crossers[[i]]){
      segments(zxmit, xmit[i], zrcv, xcoord, lwd=2)
      }
    }
  }
testPixel(c(0,0))
testPixel(c(1,2))
testPixel(c(2,4))
testPixel(c(5,5))
```
